### ISSUE TITLE
The "default" option must be set

### ISSUE THREAD

**Issue by blancomaberino** [ph-il/geolocation-bundle#1]
Hi,

Despite of installing it as shown in the page, i am getting the error in the subject.

I tried to debug the error and found that: $config in PhilGeolocationExtension.php is always empty.

Any idea about what the issue can be? 

Thanks,

**Comment by fvezzoso** [comment]
Hi @blancomaberino,

That's probably because you only have one connection and don't have a default defined in your config.yml.

The structure of the dbal config should be something like this:

```yaml
doctrine:
    dbal:
        default_connection: default
        types:
            point: Phil\GeolocationBundle\ORM\PointType
        connections:
            default:
                ...
                ...
                ...
                mapping_types: { point: point }
```

Let me know if that helps.
